### ISSUE TITLE
trigger bot new key and itself just dosent work

### ISSUE THREAD

**Issue by ghost** [rogueeeee/csgo_external_cs#1]
how do i fix it

**Comment by u16rogue** [comment]
Can you provide any information as to what changes have you made? If it's an issue with the key code please make sure that you're using the right virtual key code for your desired key. If the issue persist I dont mind looking into it further ( I no longer work on this project ). Also would like to apologize for the very late response.

**Comment by ghost** [comment]
when i click the button to change key and stuff it dosent work

**Comment by ghost** [comment]
and it dosent actvate

**Comment by u16rogue** [comment]
The GUI for changing key doesn't work. iirc I've disabled GUI components that were not implemented. By default the triggerbot key is the ALT key, if you want to change it you have to manual change it at the source.

The variable is at: https://github.com/rogueeeee/csgo_external_cs/blob/master/Hacks/Triggerbot.cs#L21

**Comment by ghost** [comment]
ok thanks
